name: Build Web App - ToDoExpress.Web
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: |
          cd ToDoExpress.Web
          npm install
      - name: ESLint Verification
        run: |
          cd ToDoExpress.Web
          npx eslint .
      - name: Build project assets
        run: |
          cd ToDoExpress.Web
          npm run build
